@echo off
echo Installing requirements...
pip install -r requirements.txt

echo Starting Flask server...
start cmd /k "python server.py"

echo Starting Telegram bot...
start cmd /k "python app.py"

echo Both servers are starting...
echo Flask server will be available at http://localhost:5000
echo Telegram bot is running... 